#!/bin/bash

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

echo
printf "\033[1;32mWelcome to %s (%s).\n\033[0m" "$DISTRIB_DESCRIPTION" "$(uname -r)"
echo
